import { makeStyles } from '@material-ui/core/styles';

export default makeStyles({
  chip: {
    color: 'white',
  },
  PHP: { backgroundColor: '#3f51b5' },
  Javascript: { backgroundColor: '#ffeb3b' },
  Python: { backgroundColor: '#2196f3' },
  Flask: { backgroundColor: '#9e9e9e' },
  C: { backgroundColor: '#ffeb3b' },
  'C++': { backgroundColor: '#ffc107' },
  Golang: { backgroundColor: '#ffc107' },
  React: { backgroundColor: '#03a9f4' },
  Node: { backgroundColor: '#8bc34a' },
  Express: { backgroundColor: '#607d8b' },
  MongoDB: { backgroundColor: '#4caf50' },
  Vue: { backgroundColor: '#009688' },
  Angular: { backgroundColor: '#f44336' },
  MySQL: { backgroundColor: '#00bcd4' },
  PostgreSQL: { backgroundColor: '#0097a7' },
  Ruby: { backgroundColor: '#e91e63' },
  Sinatra: { backgroundColor: '#263238' },
  Scala: { backgroundColor: '#795548' },
  Scalatra: { backgroundColor: '#ff5722' },
  Slim: { backgroundColor: '#795548' },
  Rust: { backgroundColor: '#673ab7' },
  Java: { backgroundColor: '#ff9800' },
  Crow: { backgroundColor: '#cddc39' },
});
